### ISSUE TITLE
간헐적 db 접속 오류 수정

### ISSUE THREAD

**Issue by ricepotato** [ricepotato/quant-invest#1]
qi-server 

간헐적 db 접속 오류 수정...

오랬동안 접속 안하고 있다가 다시 요청하면 가끔 database 오류 발생함

**Comment by ricepotato** [comment]
[2019-09-23 09:40:37,553] ERROR in app: Exception on /stock/KOSPI/2018 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./resources/stock.py", line 28, in get
    res = {"stock_list":self._get_stock_data(market, **kwargs),
  File "./resources/stock.py", line 52, in _get_stock_data
    res = self.stock_data.get_data(market, **kwargs)
  File "./stdata.py", line 25, in get_data
    res = self.rank.get_rank(data)[:limit]
  File "./data/rank.py", line 120, in get_rank
    sorted_data = sorted(self.data, key=cmp_to_key(cmp))
TypeError: 'NoneType' object is not iterable
[pid: 16|app: 0|req: 5/14] 172.25.0.4 () {36 vars in 458 bytes} [Mon Sep 23 09:40:37 2019] GET /stock/KOSPI/2018 =>
 generated 37 bytes in 6 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)

오류 로그

**Comment by ricepotato** [comment]
wait_timeout = 720000 으로 설정 변경
